Implementa melhorias na landing page
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #129
Opened 2023-10-12 16:30 UTC by gabrielrnascimento

- Melhora o layout do menu lateral na tela mobile.
- Aplica uma camada acinzentada na página na camada inferior quando o menu lateral é aberto 

## Exemplo de responsividade da página e alterações de layout
https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/e7969b94-f09d-4eae-b9ae-329058c6c5fd

2023-10-12 17:39 UTC, joaozarate requested changes

2023-10-12 17:39 UTC, joaozarate commented on src/css/index.css
> +        /*object-fit: cover;*/
É necessário manter este código cometado aqui?

2023-10-12 17:39 UTC, joaozarate commented on src/css/index.css
> +    /*background-color: #274C77;*/
É necessário manter este código cometado aqui?

2023-10-12 17:42 UTC, joaozarate commented on src/index.html
>  <script src="./js/index.js"></script>
Não iríamos remover o javascript neste momento e utilizar o css? Apenas por agora?

Se acham que pode ficar, por mim tudo bem também.

2023-10-12 17:47 UTC, gabrielrnascimento commented on src/index.html
>  <script src="./js/index.js"></script>
Eu tentei aproveitar o que já estava pronto, acho que se optarmos por remover o js poderia acarretar em adaptar algumas coisas, foi mais uma decisão pensando no tempo que levaria para adaptar para html e css puro mesmo.

Como foi dito ontem na reunião que poderíamos usar js, se achassemos necessário, não vi problema em continuar utilizando esse script.

2023-10-12 17:59 UTC, gabrielrnascimento commented on src/css/index.css
> +        /*object-fit: cover;*/
Esqueci de remover, vou atualizar

2023-10-12 17:59 UTC, gabrielrnascimento commented on src/css/index.css
> +    /*background-color: #274C77;*/
Vou remover também

2023-10-12 19:31 UTC, AliceAbreu reviewed
Gabriel, eu só achei que ficou estranha a imagem no meio da página com a borda branca nas laterais. Também a parte que o texto sobe para cima da imagem e depois desce e a imagem fica  somente com a borda de cima arredondada. Seria legal se deixasse a imagem na página inteira e se mantivesse o texto sempre embaixo da imagem.  O que acha?

2023-10-12 21:28 UTC, joaozarate commented
> Gabriel, eu só achei que ficou estranha a imagem no meio da página com a borda branca nas laterais. Também a parte que o texto sobe para cima da imagem e depois desce e a imagem fica somente com a borda de cima arredondada. Seria legal se deixasse a imagem na página inteira e se mantivesse o texto sempre embaixo da imagem. O que acha?

Não sei bem sobre a imagem por inteiro @AliceAbreu. Fica desproporcional o tamanho e deu uma scrollbar desnecessário

2023-10-13 00:28 UTC, joaozarate approved these changes
🚀

2023-10-13 00:33 UTC, AliceAbreu approved these changes

2023-10-13 00:38 UTC, arondightt approved these changes

2023-10-13 15:18 UTC, gabrielrnascimento commented on src/index.html
> +        </div>
Verdade, implementei essa alteração no último commit

2023-10-13 15:18 UTC, merged