[RF-01][RF-02] - Adiciona arquivos da tela cadastrar ong.
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #138
Opened 2023-10-22 23:42 UTC by joaozarate

2023-10-23 01:22 UTC, arondightt commented
acho que precisa alinhar um pouco o cep, junto da cidade acho que ficaria bom um campo 'estado'
![Captura de tela 2023-10-22 222132](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/76788546/dab1b4ab-78e9-45cb-bf3d-ca24db902fe8)

2023-10-23 04:13 UTC, arondightt requested changes

2023-10-23 04:13 UTC, arondightt commented on src/pages/cadastrar-ong/cadastrar-ong-1.html
> +            <img src="../../assets/images/logo-conecta.png" alt="Logo Conecta">
o logo não apareceu
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/76788546/24fcb078-07f7-4f1f-bee9-71fb3ba68875)

2023-10-23 04:13 UTC, arondightt commented on src/pages/cadastrar-ong/cadastrar-ong-1.html
> +        <div class="menu-toggle open-menu" id="">
não apareceu o menu

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/76788546/8ebec1fa-b4a6-499f-88e0-075aa6ebb2b3)

2023-10-23 19:16 UTC, AliceAbreu commented
Ficou bem legal João. Eu só acho que a linha para digitar está muito longe da descrição do campo, Por exemplo, a palavra "nome" está muito longe da linha de digitar o nome. Talvez alinha isso em cima da linha ou mais próximo.

2023-10-23 21:55 UTC, gabrielrnascimento requested changes

2023-10-23 21:55 UTC, gabrielrnascimento commented on src/pages/cadastrar-ong/cadastrar-ong.css
> +        height: 100%;
```suggestion
```

Essa linha está fazendo com que o fundo não seja aplicado em toda a página da versão mobile, remoendo ele é aplicado corretamente

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/cb14c68d-95fe-4b90-bc21-b3406b245d2c)

2023-10-28 18:58 UTC, joaozarate commented on src/pages/cadastrar-ong/cadastrar-ong-1.html
> +            <img src="../../assets/images/logo-conecta.png" alt="Logo Conecta">
Não apareceu, pois não o coloquei , quando o merge for feito irá aparecer. Para evitar de duplicar arquivos e conflitos de merge

2023-10-28 18:59 UTC, joaozarate commented on src/pages/cadastrar-ong/cadastrar-ong-1.html
> +        <div class="menu-toggle open-menu" id="">
Não apareceu, pois não o coloquei as imagens, quando o merge for feito irá aparecer. Para evitar de duplicar arquivos e conflitos de merge

2023-10-28 20:49 UTC, joaozarate commented
@AliceAbreu @arondightt @gabrielrnascimento as modificações foram feitas e esta aplicado o componente `header-component`

Mudei um pouco o formulário
Adicionei o campo check de senha
Não mais temos dois componentes para preencher na mesma row

2023-10-28 22:20 UTC, arondightt approved these changes

2023-10-29 01:24 UTC, AliceAbreu reviewed
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/141672388/6ee07bb4-e947-4b17-aa5f-6ff1ad43b5b6)


- João acho que ficaria legal manter o título padrão, adicionar cor azul #274C77 e aumentar a fonte para 40pxç
- Também acho que ficaria melhor deixar a fonte das labels em 20px;
- Mudar a palavra Email para E-mail.

O que acha?

2023-10-29 01:28 UTC, AliceAbreu reviewed
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/141672388/c7625c0f-7f25-4ffe-9f37-aa40fd6b1669)


- Na outra página também poderia mudar o título para azul #274C77 e font-size 40px
- Poderia mudar a font-size dos labels para 20px. O que acha?

2023-10-29 02:09 UTC, joaozarate commented
> * João acho que ficaria legal manter o título padrão, adicionar cor azul #274C77 e aumentar a fonte para 40pxç
> * Também acho que ficaria melhor deixar a fonte das labels em 20px;
> * Mudar a palavra Email para E-mail.
> 
> O que acha?

@AliceAbreu 
- o font-size de 20px ficou grande demais
- O email foi corrigido
- e o titulo foi corrigido seguindo aqui: [link](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/blob/main/src/pages/pagina-de-demandas/pagina-de-demandas.html#L25)

2023-10-29 02:10 UTC, joaozarate commented
> ![image](https://user-images.githubusercontent.com/141672388/278846337-c7625c0f-7f25-4ffe-9f37-aa40fd6b1669.png)
> 
> * Na outra página também poderia mudar o título para azul #274C77 e font-size 40px
> * Poderia mudar a font-size dos labels para 20px. O que acha?

@AliceAbreu idem ao comentário acima

2023-10-29 16:31 UTC, gabrielrnascimento approved these changes

2023-10-29 16:39 UTC, merged