Pagina por que ser voluntario
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #139
Opened 2023-10-23 01:09 UTC by arondightt

2023-10-23 21:32 UTC, gabrielrnascimento reviewed
Acho que está rolando um problema com a responsividade da imagem, a parte da direita vai sumindo na lateral da página.

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/ee576e1c-8d63-4034-bde7-2694644c6981)

2023-10-26 01:30 UTC, AliceAbreu reviewed
- Omar a fonte está muito grande, acho que poderia manter o padrão como está no Figma 40px para o título e 20px para o texto;

- Também acho que poderia por um line-height: 30px no texto, para ficar mas legível;
-
- Acho que a imagem está muito grande, poderia ficar 50% imagem, 50% texto. Para isso poderia colocar em content: 
    display: grid;
    grid-template-columns: 1fr 1fr;
    align-items: center;

- Poderia melhorar o texto também, tentando convencer o usuário a ser voluntário. Acho que fica legal escrever 2 parágrafos e deixar um gap entre eles.

2023-10-28 22:23 UTC, joaozarate approved these changes
Apesar do menu esta com problemas ao responder ao tamanho da tela, aprovei pois iremos usar o componente criado pelo Grabriel
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/566544/6b38572b-67a5-4748-a7e7-503a8f6c1d53)

2023-10-29 16:38 UTC, gabrielrnascimento requested changes
A página não está limitando o width igual as outras, segue o exemplo da página de "como começar"

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/2b8e31dc-491f-425d-b856-a33176d412b8)


Ela está usando toda a width da página

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/d1fab18d-4159-4b5b-8c6c-0ac70dc54386)


Acredito que o motivo seja porque no html não existe a div `container` igual nas outras páginas.

Esse aqui é um print do `como-comecar.html`, estamos usando uma div `container` para englobar todo o conteúdo da página 

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/7238a37b-49db-498f-95d5-78ad72b7d5ee)

e no `index.css` limitamos a width máxima (isso já está incluido no `index.css` não é necessário adicionar no seu código).
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/05968bf8-f329-4611-9821-c0c1e17e5853)

Só adicionar essa div `container` mesmo.

2023-10-30 00:40 UTC, AliceAbreu reviewed
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/141672388/b5e20393-a155-4745-a901-f0b0ea8d4476)

- Omar a imagem está muito na esquerda, poderia deixar ela mais centralizada dentro da div

2023-10-31 22:13 UTC, gabrielrnascimento approved these changes

2023-11-03 01:09 UTC, merged