ajustes landing page
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #146
Opened 2023-10-25 20:51 UTC by pedrocventurapuc

2023-10-25 21:59 UTC, gabrielrnascimento requested changes

2023-10-25 21:59 UTC, gabrielrnascimento commented on src/index.html
> +                                Quero ajudar
```suggestion
                                Como começar
```
O texto desse botão é "Como começar"

2023-10-25 21:59 UTC, gabrielrnascimento commented on src/index.html
> +                <div class="box">
Esse card ficou diferente do que estava no Figma.
Eu recomendo pegar o código do PR #135 que está com um card mais próximo do que fizemos no layout do Figma, pode pegar tanto o vertical quanto o horizontal.

Segue imagem dos cards do Figma:
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/f2949653-7a38-4bd6-80dc-66799ac87b51)

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/cbc1d5a3-00d6-42a1-98b9-3554380ebf11)

2023-10-25 21:59 UTC, gabrielrnascimento commented on src/index.html
> +                    <p class="text-saiba-como">Descubra diversas formas de fazer a diferença em sua comunidade.
Esser texto deve ficar na mesma linha do título dessa div.

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/d0c8beba-48da-45a3-90f5-34bcbb530ccc)

2023-10-25 21:59 UTC, gabrielrnascimento commented on src/index.html
> +                    <h3 class="title-saiba-como">Saiba como se voluntariar</h3>
- Esse texto do título precisa estar alinhado à esquerda e não centralizado.
- Também seria importante aproveitar toda a imagem no espaço disponível. Atualmente ela está diminuindo e ficamos com esse espaço abaixo dela. 

![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/0cd27be1-d45f-443d-a487-f01868f5bf86)

2023-10-25 21:59 UTC, gabrielrnascimento commented on src/index.html
> +                <h1 class="main-title">Conheça as oportunidades de voluntariado</h1>
Adicionar uma quebra de linha entre as frases nessa parte.
Segue imagem do Figma:
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/65cd9872-0402-4515-bcb8-d76f6a790c0d)

Atualmente está tudo na mesma linha:
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/5bd0790d-a2ff-4582-852d-282a9678dd51)

2023-10-25 22:33 UTC, joaozarate requested changes

2023-10-25 22:33 UTC, joaozarate commented on src/index.html
> +            </div>
Esta parte não é mais do tamanho que esta sendo apresentado. Como pode ser visto [no figma](https://www.figma.com/file/PHLai1Ms1jxrBsoUWlqAJD/Wireframe?type=design&node-id=181-96&mode=design&t=ACXo0qP44tP5aQYr-0) a proporção do texto e a imagem não corresponde ao prototipado.

2023-10-25 22:33 UTC, joaozarate commented on src/index.html
> +        <div class="content">
O content não deve ser fluido ao ponto de ocupar toda a tela, deve ter um limite assm como apresentado na [pagina-da-ong.html](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/blob/main/src/pages/pagina-da-ong/pagina-da-ong.html), como exemplo

2023-10-25 22:33 UTC, joaozarate commented on src/css/index.css
> +  }
Falta uma linha no fim do arquivo

2023-10-25 22:33 UTC, joaozarate commented on src/index.html
> +</html>
Falta uma linha no fim do arquivo

2023-10-26 15:50 UTC, arondightt requested changes

2023-10-26 15:50 UTC, arondightt commented on src/css/index.css
> +
Teve alterações no index.css, ele esta sendo usado como base de estilo para outras paginas, é interessante deixar o index.css como base e criar um novo arquivo de estilo para a Landing page.

2023-11-01 23:23 UTC, closed without merging