Tela cadastrar demanda da ong
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #152
Opened 2023-10-29 03:42 UTC by arondightt

2023-10-29 10:31 UTC, joaozarate requested changes
@arondightt deixei aqui algun scomentários

2023-10-29 10:31 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.html
> +</html>
```suggestion
</html>

```

2023-10-29 10:31 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.css
> +    border-bottom: 1px dotted #716F6F;
Precisamos repensar nesta linha na corrente tela e nas demais. Não me parece visualmente adequado.

2023-10-29 10:31 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.css
> +    font-size: 20px;
Este tamanho de letra, como havíamos discutido no whatsapp, é demasiado grande. Se o remover, por agora, ficará com um bom tamanho, mas temos que tratar isso de forma transversal às telas em um css file geral.
```suggestion
    font-size: 20px;
```

2023-10-29 10:31 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.css
> +    font-weight: 700;
Mesmo caso do tamanho da letra
```suggestion
    font-weight: 700;
```

2023-10-29 10:31 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.html
> +                </div>
A relação label + field não esta responsiva, esta sempre exibindo no modo mobile.

2023-10-29 16:44 UTC, gabrielrnascimento requested changes

2023-10-29 16:44 UTC, gabrielrnascimento commented on src/pages/cadastrar-demanda/cadastrar-demanda.html
> +                        <label for="hibrida">Híbrida</label>
Não consigo marcar o campo `Híbrida".

2023-10-30 00:19 UTC, AliceAbreu reviewed
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/141672388/903de6fe-855a-415e-a876-c10add7aa01f)

- Omar essa parte aqui está bugada;

2023-10-30 16:46 UTC, arondightt commented on src/pages/cadastrar-demanda/cadastrar-demanda.html
> +                        <label for="hibrida">Híbrida</label>
resolvido

2023-10-31 22:24 UTC, gabrielrnascimento requested changes

2023-10-31 22:24 UTC, gabrielrnascimento commented on src/pages/cadastrar-demanda/cadastrar-demanda.html
> +                        <label for="sobre-demanda">Descreva sua nescessidade:</label>
Corrigir para `necessidade`
```suggestion
                        <label for="sobre-demanda">Descreva sua necessidade:</label>
```

2023-11-01 00:30 UTC, gabrielrnascimento approved these changes

2023-11-01 21:33 UTC, joaozarate requested changes

2023-11-01 21:33 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.css
> +    width: 25%;
Acho que poderia verificar em cadastrar ong a distancia entre o label e o componente. 25% me parece demasiado.

2023-11-01 21:33 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.html
> +                <div class="row-button">
Seguindo o padrão me parece que os botões são alinhados a direita em resolução desktop. Veja no cadastrar ONg e a tela de redefinição de senha

2023-11-01 21:33 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.css
> +    resize: none;
Poderia remover o resize, pois daria a oprtunidade ao usuário de modificar o tamanho do textarea para melhor escrita do texto.

2023-11-01 21:33 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.css
> +    border-radius: 0px;
```suggestion
    border-radius: 15px;
```

2023-11-01 21:33 UTC, joaozarate commented on src/pages/cadastrar-demanda/cadastrar-demanda.css
> +    border-radius: 0px;
Temos deixado as bordas arredondadas deste componente

2023-11-01 21:34 UTC, joaozarate commented
@arondightt Deixei uns comentários

2023-11-02 01:36 UTC, arondightt commented
@joaozarate remodelei com um menor tamanho como falamos na reunião e alterei tbm conforme as sugestões, quando puder, dá uma olhada se tem outro ponto

2023-11-03 00:50 UTC, joaozarate approved these changes
🚀 LGTM

2023-11-03 01:31 UTC, merged