[RF-13] - Histórias de Sucesso
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #155
Opened 2023-10-29 17:36 UTC by joaozarate

2023-10-30 23:04 UTC, AliceAbreu commented
- João, adicionei as alterações em Histórias de Sucesso. Não sei como você colocou umas linhas brancas dividindo as divs quando faz o scroll. Eu tentei tirar, mas não consegui.

2023-10-31 22:09 UTC, gabrielrnascimento requested changes
Para corrigir as linhas brancas fiz essas alterações marcadas na foto.

Na parte de baixo, apenas adaptei a hierarquia do css para considerar a tag `main`
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/59718237/94fe87c6-3979-47e4-8553-8aeac0b8e3f3)

2023-10-31 22:09 UTC, gabrielrnascimento commented on src/pages/historias-sucesso/historias-sucesso.css
> +    transition: transform 0.2s;
Acho que ficaria legal se usássemos o `object-fit: cover;` aqui, assim a imagem ia se adaptando de acordo com o espaço e não perderia o aspect ratio.

2023-10-31 22:53 UTC, AliceAbreu commented on src/pages/historias-sucesso/historias-sucesso.css
> +    transition: transform 0.2s;
Corrigido!

2023-10-31 22:59 UTC, gabrielrnascimento approved these changes

2023-11-01 00:14 UTC, arondightt approved these changes

2023-11-01 03:00 UTC, merged