Comunicação HTTP e Objetos de domínio
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #216
Opened 2023-11-11 21:14 UTC by gabrielrnascimento

- Adiciona package.json juntamente com `json-server`
- Cria o "banco de dados" para testes durante o desenvolvimento (com dados mockados para testes)
- Cria os objetos de domínio, basicamente classes para abstrair operações e simplificar as operações de CRUD.

2023-11-12 15:52 UTC, joaozarate requested changes

2023-11-12 15:52 UTC, joaozarate commented on src/js/http.js
> +    if (!['GET', 'POST', 'PUT', 'DELETE'].includes(upperCaseMethod)) {
Acho que aqui pode incluir o PATCH

2023-11-12 16:01 UTC, joaozarate commented
nit: Seria bom termos um linha em branco no fim dos arquivos novos para manter os padões do github

2023-11-12 17:37 UTC, gabrielrnascimento commented on src/js/http.js
> +    if (!['GET', 'POST', 'PUT', 'DELETE'].includes(upperCaseMethod)) {
Adicionado esse método

2023-11-15 22:13 UTC, joaozarate approved these changes

2023-11-15 22:19 UTC, AliceAbreu approved these changes

2023-11-15 23:11 UTC, merged