Historia de usuario Ana L
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #22
Opened 2023-09-12 18:05 UTC by arondightt

cria a historia de usuario da Persona Ana Lucia

2023-09-12 20:17 UTC, joaozarate requested changes

2023-09-12 20:17 UTC, joaozarate commented on docs/especification.md
> +<<<<<<< Updated upstream
Este caracteres não podem ser merged, pois são indicadores de conflito e precisam ser resolvidos manualmente.

Cuidado para não remover informações que já estão consolidaddas na main

2023-09-12 20:17 UTC, joaozarate commented on docs/especification.md
> +=======
Este caracteres não podem ser merged, pois são indicadores de conflito e precisam ser resolvidos manualmente.

Cuidado para não remover informações que já estão consolidaddas na main

2023-09-13 01:00 UTC, joaozarate requested changes

2023-09-13 01:18 UTC, arondightt commented on docs/especification.md
> +![Alt text](./img/personas/heitor-persona.jpg)
Foi alterado a imagem da Persona Ana Lucia e a outra eu acho que mudei o "Alt text"

2023-09-13 01:18 UTC, arondightt commented on docs/especification.md
> +![Alt text](./img/personas/heitor-persona.jpg)
Acha melhor criar nova PR?

2023-09-13 01:30 UTC, closed without merging