Funcionalidade: Candidatar a demanda 2
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #298
Opened 2023-12-04 01:01 UTC by arondightt

- Adiciona mascara no telefone e cpf
- confere se usuário possui 2 candidaturas entre pendente e aprovado
- confere se a candidatura tem mais de 3 dias
- pega taskId da demanda no url
- adiciona o nome da ong atraves do ongId no url
- cadastra usuário

2023-12-04 20:32 UTC, AliceAbreu commented on docs/tests.md
> +**Procedimento**  | 1) Acessar a página `candidatar a demanda`  <br> 2) Insere dados validos <br> 3) Clique no botão `Enviar` <br>
Poderia colocar o link da página. 

- Acessar a página [candidatar a demanda](https://icei-puc-minas-pmv-si.github.io/pmv-si-2023-2-pe1-t2-conecta/pages/candidatar-a-demanda/candidatar-a-demanda.html?id=2).

- Corrigir 'validos' para 'válidos'.

2023-12-04 20:33 UTC, AliceAbreu commented on docs/tests.md
> +**Resultado esperado** | O usuario se candidata a demanda escolhida
- Corrigir 'O usuario se candidata a demanda escolhida' para 'O usuário se candidata à demanda escolhida'.

2023-12-04 23:35 UTC, joaozarate commented
⚠️ do not merge

2023-12-05 23:27 UTC, joaozarate approved these changes

2023-12-05 23:30 UTC, gabrielrnascimento requested changes

2023-12-05 23:30 UTC, gabrielrnascimento commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +        const numberOfRegistrations = await countRegistrationsByCpf(cpf);
Acredito que esse teste também deve ocorrer após o usuário clicar no botão

2023-12-05 23:30 UTC, gabrielrnascimento commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +const getOrganizationId = () => {
O botão `QUERO AJUDAR` adiciona apenas o `id` no final da URL, esse id se refere ao id da task, você pode usar o id da task para encontrar o id da ONG, não é necessário que esse parâmetro seja passado na URL.

A task no banco é armazenada com o `organizationId`

https://orca-app-fbvzt.ondigitalocean.app/tasks

2023-12-05 23:55 UTC, arondightt commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +        const numberOfRegistrations = await countRegistrationsByCpf(cpf);
ué, ele ocorre
![image](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta/assets/76788546/0be29b44-a21a-47fe-8e2a-7124ebfd748f)
na função handleSend

2023-12-06 00:08 UTC, arondightt commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +            alert("CPF inválido. Por favor, verifique o número e tente novamente.");
feito

2023-12-06 01:05 UTC, arondightt commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +const getTaskId = () => {
corrigido

2023-12-06 01:06 UTC, arondightt commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +const getOrganizationId = () => {
feito

2023-12-06 16:33 UTC, merged