Cadastrar depoimento
ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta pull request #313
Opened 2023-12-05 20:02 UTC by joaozarate

2023-12-05 23:40 UTC, joaozarate commented on src/js/models/review.js
> +            expiresAt: new Date(Date.now() + 7200000),
Podemos manter 2h ou menos para finz academicos

2023-12-05 23:44 UTC, joaozarate commented on src/js/models/review.js
> +    return await makeRequest(getURL(`reviews/${id}`), 'PATCH', data);
Utilizei patch pois era o unico http verb que não havíamos utilizado

2023-12-06 00:42 UTC, gabrielrnascimento requested changes

2023-12-06 00:42 UTC, gabrielrnascimento commented on src/pages/administrar-demanda/administrar-demanda.js
> +                `Olá ${candidate.name}, a ONG ${organizationData.name} gostaria de saber como foi sua experiência de voluntariado. <br> <br> Compartilhe sua experiência através desse link: ${PROJECT_
Remoer o `}` avulso no final do email

2023-12-06 00:42 UTC, gabrielrnascimento commented on src/pages/administrar-demanda/administrar-demanda.js
> +                `Olá ${candidate.name}, a ONG ${organizationData.name} gostaria de saber como foi sua experiência de voluntariado. <br> <br> Compartilhe sua experiência através desse link: ${PROJECT_
No final dessa url, o query param enviado é `token=` mas no arquivo `cadastrar-depoimneto.js` está sendo buscado um `id` no query param.

Na linha 245 dessa arquivo também está sendo enviado um `id=` como query param.

Acho que o melhor é mudar esse query param acima para `id=`

2023-12-06 00:42 UTC, gabrielrnascimento commented on src/js/models/review.js
> +        comment: comment,
É preciso enviar também a data que o depoimento foi enviado, atualmente não está enviando nada e na página na ONG, na listagem de depoimentos, é retornado um Invalid Date

na página da ONG é esperado receber um `createdAd`

2023-12-06 01:03 UTC, joaozarate commented on src/js/models/review.js
> +        comment: comment,
Feito @gabrielrnascimento

2023-12-06 11:55 UTC, merged